//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 12:19:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springsoapexample.chandimal.com/dtos/marks", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.chandimal.springsoapexample.dtos.marks;
